# Generated by Django 3.0.3 on 2020-02-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(null=True, upload_to='user/'),
        ),
    ]
